
kind: ConfigMap
apiVersion: v1
metadata:
  name: backend
  namespace: expense
data:
  DB_HoST: mysql  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
# These are deployment resource labels.  
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: yeguru/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend  
---
kind: Service
apiVersion: v1
metadata:
  name: backend
  namespace: expense
spec:
  selector:     #labels are used as selectors
    app: backend
    tier: backend
    project: expense
  ports:
  - protocol: TCP
    port: 8080  #service port
    targetPort: 8080